import os

'''游戏参数定义'''
WIDTH = 800
HEIGHT = 800
VOLUME = 1
NUMGRID = 10
GRIDSIZE = 64
XMARGIN = (WIDTH - GRIDSIZE * NUMGRID) // 2
YMARGIN = (HEIGHT - GRIDSIZE * NUMGRID) // 2
RCTTOP = 200
FPS = 30